SCR_Faction : "{7D3FEF4E243F3587}Configs/Factions/Charlie/Charlie_Faction_Base.conf" {
 FactionKey "Bandit"
 UIInfo SCR_FactionUIInfo "{66493AE5A64FA07C}" {
  Name "Bandit"
  Icon "{3B522C0E43AD1D11}Images/Charlie_1.edds"
  m_sNameUpper "BANDIT"
 }
 m_iOrder 5
 m_bIsPlayable 0
 m_sFactionFlag "{3B522C0E43AD1D11}Images/Charlie_1.edds"
 m_CallsignInfo SCR_FactionCallsignInfo "{66493AE743F887BC}" : "{9B9D306B0A9A6B46}Configs/Callsigns/Callsigns_Bandit.conf" {
  m_sCallsignGroupFormat "%3"
  m_sCallsignCharacterFormat "%3"
  m_sCallsignCharacterWithRoleFormat ""
 }
 m_aPredefinedGroups {
  SCR_GroupPreset "{66493AEDAF233FC8}" {
   m_sGroupName "Bandit-6"
   m_sGroupDescription "PL, RTO"
   m_iGroupSize 2
   m_iRadioFrequency 50200
  }
  SCR_GroupPreset "{66493AEDAFC16A72}" {
   m_sGroupName "Bandit-5"
   m_sGroupDescription "PSG, RTO"
   m_iGroupSize 2
   m_iRadioFrequency 50200
  }
  SCR_GroupPreset "{66493AEDAFE59674}" {
   m_sGroupName "Bandit-7"
   m_sGroupDescription "PLT Medic, Medic"
   m_iGroupSize 2
   m_iRadioFrequency 50200
  }
  SCR_GroupPreset "{66493AEDAFAC7F19}" {
   m_sGroupName "Bandit-1"
   m_sGroupDescription "Maneuver Infantry Squad"
   m_iGroupSize 9
   m_iRadioFrequency 51000
  }
  SCR_GroupPreset "{66493AEDAE5B85E9}" {
   m_sGroupName "Bandit-2"
   m_sGroupDescription "Maneuver Infantry Squad"
   m_iGroupSize 9
   m_iRadioFrequency 51200
  }
  SCR_GroupPreset "{66493AEDAE141B7A}" {
   m_sGroupName "Bandit-3"
   m_sGroupDescription "Maneuver Infantry Squad"
   m_iGroupSize 9
   m_iRadioFrequency 51400
  }
  SCR_GroupPreset "{66493AEDAEAA4248}" {
   m_sGroupName "Bandit-4"
   m_sGroupDescription "Weapons Squad"
   m_iGroupSize 9
   m_iRadioFrequency 51600
  }
 }
 m_iFactionRadioFrequency 50000
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{66496EB732D85F98}" {
   m_aMultiLists {
    SCR_EntityCatalogMultiListEntry "{664967E60DEF10C2}" {
     m_aEntities {
      SCR_EntityCatalogEntry "{66497B346944C439}" {
       m_bEnabled 1
      }
     }
    }
   }
  }
 }
}