SCR_Faction : "{7D3FEF4E243F3587}Configs/Factions/Charlie/Charlie_Faction_Base.conf" {
 FactionKey "Misfit"
 UIInfo SCR_FactionUIInfo "{66493AE5A64FA07C}" {
  Name "Misfit"
  Icon "{65BA054DFC20931E}Images/Charlie_2.edds"
  m_sNameUpper "MISFIT"
 }
 m_iOrder 6
 m_sFactionFlag "{65BA054DFC20931E}Images/Charlie_2.edds"
 m_aPredefinedGroups {
  SCR_GroupPreset "{66493AEC9288D073}" {
   m_sGroupName "Misfit-6"
   m_sGroupDescription "PL, RTO"
   m_iGroupSize 2
   m_iRadioFrequency 55200
  }
  SCR_GroupPreset "{66493AEC92AB0707}" {
   m_sGroupName "Misfit-5"
   m_sGroupDescription "PSG, RTO"
   m_iGroupSize 2
   m_iRadioFrequency 55200
  }
  SCR_GroupPreset "{66493AEC916E6CCB}" {
   m_sGroupName "Misfit-7"
   m_sGroupDescription "PLT Medic, Medic"
   m_iGroupSize 2
   m_iRadioFrequency 55200
  }
  SCR_GroupPreset "{66493AEC9108C7D2}" {
   m_sGroupName "Misfit-1"
   m_sGroupDescription "Maneuver Infantry Squad"
   m_iGroupSize 9
   m_iRadioFrequency 56000
  }
  SCR_GroupPreset "{66493AEC91365603}" {
   m_sGroupName "Misfit-2"
   m_sGroupDescription "Maneuver Infantry Squad"
   m_iGroupSize 9
   m_iRadioFrequency 56200
  }
  SCR_GroupPreset "{66493AEC91E112EF}" {
   m_sGroupName "Misfit-3"
   m_sGroupDescription "Maneuver Infantry Squad"
   m_iGroupSize 9
   m_iRadioFrequency 56400
  }
  SCR_GroupPreset "{66493AEC91A848C4}" {
   m_sGroupName "Misfit-4"
   m_sGroupDescription "Weapons Squad"
   m_iGroupSize 9
   m_iRadioFrequency 56600
  }
 }
 m_iFactionRadioFrequency 55000
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{66496EB732D85F98}" {
   m_aMultiLists {
    SCR_EntityCatalogMultiListEntry "{664967E60DEF10C2}" {
     m_aEntities {
      SCR_EntityCatalogEntry "{66497B346944C439}" {
       m_bEnabled 1
      }
     }
    }
    SCR_EntityCatalogMultiListEntry "{664967E60D93647E}" {
     m_aEntities {
      SCR_EntityCatalogEntry "{66497B3FEAD79270}" {
       m_sEntityPrefab "{4A11957AAD447582}Prefabs/Characters/Vests/Vest_JPC/Vest_JPC_MC.et"
      }
     }
    }
   }
  }
 }
}