SCR_Faction : "{7D3FEF4E243F3587}Configs/Factions/Charlie/Charlie_Faction_Base.conf" {
 FactionKey "Gunslinger"
 UIInfo SCR_FactionUIInfo "{66493AE5A64FA07C}" {
  Name "Gunslinger"
  m_sNameUpper "GUNSLINGER"
 }
 m_iOrder 7
 m_CallsignInfo SCR_FactionCallsignInfo "{66493AE743F887BC}" : "{385C9CDC23CAFA1E}Configs/Callsigns/Callsigns_Gunslinger.conf" {
  m_sCallsignCharacterWithRoleFormat ""
 }
 m_aPredefinedGroups {
  SCR_GroupPreset "{66493AE3E564B4B2}" {
   m_sGroupName "Gunslinger-6"
   m_sGroupDescription "PL, RTO"
   m_iGroupSize 2
   m_iRadioFrequency 48200
  }
  SCR_GroupPreset "{66493AE3E509467E}" {
   m_sGroupName "Gunslinger-5"
   m_sGroupDescription "PSG, RTO"
   m_iGroupSize 2
   m_iRadioFrequency 48200
  }
  SCR_GroupPreset "{66493AE3E52ECE13}" {
   m_sGroupName "Gunslinger-7"
   m_sGroupDescription "PLT Medic, Medic"
   m_iGroupSize 2
   m_iRadioFrequency 48200
  }
  SCR_GroupPreset "{66493AE3E535DA60}" {
   m_sGroupName "Gunslinger-1"
   m_sGroupDescription "Maneuver Infantry Squad"
   m_iGroupSize 9
   m_iRadioFrequency 49000
  }
  SCR_GroupPreset "{66493AE3E5F096D6}" {
   m_sGroupName "Gunslinger-2"
   m_sGroupDescription "Maneuver Infantry Squad"
   m_iGroupSize 9
   m_iRadioFrequency 49200
  }
  SCR_GroupPreset "{66493AE3E5BA2708}" {
   m_sGroupName "Gunslinger-3"
   m_sGroupDescription "Maneuver Infantry Squad"
   m_iGroupSize 9
   m_iRadioFrequency 49400
  }
  SCR_GroupPreset "{66493AE3E429F0F5}" {
   m_sGroupName "Gunslinger-4"
   m_sGroupDescription "Weapons Squad"
   m_iGroupSize 9
   m_iRadioFrequency 49600
  }
 }
}