SCR_FactionCallsignInfo {
 m_bIsAssignedRandomly 0
 m_aCompanyNames {
  SCR_CallsignInfo "{68B70BB5DEF6B45F}" {
   m_sCallsign "7CAV "
  }
 }
 m_iCompanyOverflowIndex 1
 m_aPlatoonNames {
  SCR_CallsignInfo "{68B70BB5DEF6B447}" {
   m_sCallsign " Drill Instructors"
  }
  SCR_CallsignInfo "{68B70BB5DEF6B444}" {
   m_sCallsign "Recruits"
  }
 }
 m_aSquadNames {
  SCR_CallsignInfo "{68B70BB5DEF6B445}" {
   m_sCallsign "Misfit-6"
  }
  SCR_CallsignInfo "{68B70BB5DEF6B44A}" {
   m_sCallsign "Misfit-5"
  }
  SCR_CallsignInfo "{68B70BB5DEF6B55F}" {
   m_sCallsign "Misfit-7"
  }
  SCR_CallsignInfo "{68B70BB5DEF6B55E}" {
   m_sCallsign "Misfit-1"
  }
  SCR_CallsignInfo "{68B70BB5DEF6B55D}" {
   m_sCallsign "Misfit-2"
  }
  SCR_CallsignInfo "{68B70BB5DEF6B55C}" {
   m_sCallsign "Misfit-3"
  }
  SCR_CallsignInfo "{68B70BB5DEF6B55B}" {
   m_sCallsign "Misfit-4"
  }
 }
 m_sCallsignGroupFormat "%3"
 m_sCallsignCharacterFormat "%3"
 m_aCharacterRoleCallsigns {
  SCR_LeaderRoleCallsign "{68B70BB5DEF6B55A}" {
   m_sRoleName "#AR-Callsign_US_SquadLeader"
  }
  SCR_RadioOperatorRoleCallsign "{68B70BB5DEF6B559}" {
   m_sRoleName "#AR-Callsign_US_RadioOperator"
  }
  SCR_PlayerLeaderRoleCallsign "{68B70BB5DEF6B558}" {
   m_bEnabled 0
   m_sRoleName "#AR-Callsign_US_SquadLeader"
   m_eRoleAvailableForCharacterType PLAYER_ONLY
  }
 }
}