SCR_FactionCallsignInfo {
 m_bIsAssignedRandomly 0
 m_aCompanyNames {
  SCR_CallsignInfo "{68B70BB11B530966}" {
   m_sCallsign "7CAV "
  }
 }
 m_iCompanyOverflowIndex 1
 m_aPlatoonNames {
  SCR_CallsignInfo "{68B70BB11B53096A}" {
   m_sCallsign " Drill Instructors"
  }
  SCR_CallsignInfo "{68B70BB11B530969}" {
   m_sCallsign "Recruits"
  }
 }
 m_aSquadNames {
  SCR_CallsignInfo "{68B70BB11B530968}" {
   m_sCallsign "Pioneer-6"
  }
  SCR_CallsignInfo "{68B70BB11B530977}" {
   m_sCallsign "Pioneer-5"
  }
  SCR_CallsignInfo "{68B70BB11B53CC63}" {
   m_sCallsign "Pioneer-7"
  }
  SCR_CallsignInfo "{68B70BB11B53CC62}" {
   m_sCallsign "Pioneer-1"
  }
  SCR_CallsignInfo "{68B70BB11B53CC61}" {
   m_sCallsign "Pioneer-2"
  }
  SCR_CallsignInfo "{68B70BB11B53CC60}" {
   m_sCallsign "Pioneer-3"
  }
  SCR_CallsignInfo "{68B70BB11B53F4E0}" {
   m_sCallsign "Pioneer-4"
  }
 }
 m_sCallsignGroupFormat "%3"
 m_sCallsignCharacterFormat "%3"
 m_aCharacterRoleCallsigns {
  SCR_LeaderRoleCallsign "{68B70BB11B53F4E6}" {
   m_sRoleName "#AR-Callsign_US_SquadLeader"
  }
  SCR_RadioOperatorRoleCallsign "{68B70BB11B53F4E5}" {
   m_sRoleName "#AR-Callsign_US_RadioOperator"
  }
  SCR_PlayerLeaderRoleCallsign "{68B70BB11B53B1E4}" {
   m_bEnabled 0
   m_sRoleName "#AR-Callsign_US_SquadLeader"
   m_eRoleAvailableForCharacterType PLAYER_ONLY
  }
 }
}