SCR_FactionCallsignInfo {
 m_bIsAssignedRandomly 0
 m_aCompanyNames {
  SCR_CallsignInfo "{68B45B802E409F65}" {
   m_sCallsign "7CAV "
  }
 }
 m_iCompanyOverflowIndex 1
 m_aPlatoonNames {
  SCR_CallsignInfo "{68B4561C905E87F3}" {
   m_sCallsign " Drill Instructors"
  }
  SCR_CallsignInfo "{68B4561C905E87F0}" {
   m_sCallsign "Recruits"
  }
 }
 m_aSquadNames {
  SCR_CallsignInfo "{68B4561C905E87F1}" {
   m_sCallsign "Drill Instructors"
  }
  SCR_CallsignInfo "{68B4561C905E878F}" {
   m_sCallsign "Recruits"
  }
  SCR_CallsignInfo "{68B4561C905E878C}" {
   m_sCallsign "3"
  }
  SCR_CallsignInfo "{68B4561C905E878D}" {
   m_sCallsign "4"
  }
 }
 m_sCallsignGroupFormat "%3"
 m_sCallsignCharacterFormat "%3"
 m_aCharacterRoleCallsigns {
  SCR_LeaderRoleCallsign "{68B4561C905E8789}" {
   m_sRoleName "#AR-Callsign_US_SquadLeader"
  }
  SCR_RadioOperatorRoleCallsign "{68B4561C905E8796}" {
   m_sRoleName "#AR-Callsign_US_RadioOperator"
  }
  SCR_PlayerLeaderRoleCallsign "{68B4561C905E8797}" {
   m_bEnabled 0
   m_sRoleName "#AR-Callsign_US_SquadLeader"
   m_eRoleAvailableForCharacterType PLAYER_ONLY
  }
 }
}