SCR_FactionCallsignInfo {
 m_bIsAssignedRandomly 0
 m_aCompanyNames {
  SCR_CallsignInfo "{68B70BBDDFF75C9D}" {
   m_sCallsign "7CAV "
  }
 }
 m_iCompanyOverflowIndex 1
 m_aPlatoonNames {
  SCR_CallsignInfo "{68B70BBDDFF75C90}" {
   m_sCallsign " Drill Instructors"
  }
  SCR_CallsignInfo "{68B70BBDDFF75C91}" {
   m_sCallsign "Recruits"
  }
 }
 m_aSquadNames {
  SCR_CallsignInfo "{68B70BBDDFF75C92}" {
   m_sCallsign "Chaos-1"
  }
  SCR_CallsignInfo "{68B70BBDDFF75C93}" {
   m_sCallsign "Buffalo-1"
  }
  SCR_CallsignInfo "{68B70BBDDFF75CAC}" {
   m_sCallsign "Buffalo-2"
  }
  SCR_CallsignInfo "{68B70BBDDFF739D3}" {
   m_sCallsign "Grizzly-1"
  }
  SCR_CallsignInfo "{68B70BBDDFF739D2}" {
   m_sCallsign "Grizzly-2"
  }
  SCR_CallsignInfo "{68B70BBDDFF739D1}" {
   m_sCallsign "Raven-1"
  }
  SCR_CallsignInfo "{68B70BBDDFF739D0}" {
   m_sCallsign "Raven-2"
  }
  SCR_CallsignInfo "{68B70BBDDFF492D4}" {
   m_sCallsign "Sparrow-1"
  }
  SCR_CallsignInfo "{68B70BBDDFF492D3}" {
   m_sCallsign "Sparrow-2"
  }
  SCR_CallsignInfo "{68B70BBE3878C5EA}" {
   m_sCallsign "Bison-1"
  }
  SCR_CallsignInfo "{68B70BBDDFF448D0}" {
   m_sCallsign "Raider-1"
  }
  SCR_CallsignInfo "{68B70BBDDFF448C5}" {
   m_sCallsign "Raider-2"
  }
 }
 m_sCallsignGroupFormat "%3"
 m_sCallsignCharacterFormat "%3"
 m_aCharacterRoleCallsigns {
  SCR_LeaderRoleCallsign "{68B70BBDDFF448C6}" {
   m_sRoleName "#AR-Callsign_US_SquadLeader"
  }
  SCR_RadioOperatorRoleCallsign "{68B70BBDDFF448C7}" {
   m_sRoleName "#AR-Callsign_US_RadioOperator"
  }
  SCR_PlayerLeaderRoleCallsign "{68B70BBDDFF448C0}" {
   m_bEnabled 0
   m_sRoleName "#AR-Callsign_US_SquadLeader"
   m_eRoleAvailableForCharacterType PLAYER_ONLY
  }
 }
}