SCR_FactionCallsignInfo {
 m_bIsAssignedRandomly 0
 m_aCompanyNames {
  SCR_CallsignInfo "{68B70BB5E5567CE7}" {
   m_sCallsign "7CAV "
  }
 }
 m_iCompanyOverflowIndex 1
 m_aPlatoonNames {
  SCR_CallsignInfo "{68B70BB5E5567CF3}" {
   m_sCallsign " Drill Instructors"
  }
  SCR_CallsignInfo "{68B70BB5E5567CF5}" {
   m_sCallsign "Recruits"
  }
 }
 m_aSquadNames {
  SCR_CallsignInfo "{68B70BB5E5562B1F}" {
   m_sCallsign "Bandit-6"
  }
  SCR_CallsignInfo "{68B70BB5E5562B1D}" {
   m_sCallsign "Bandit-5"
  }
  SCR_CallsignInfo "{68B70BB5E557E335}" {
   m_sCallsign "Bandit-7"
  }
  SCR_CallsignInfo "{68B70BB5E557E33B}" {
   m_sCallsign "Bandit-1"
  }
  SCR_CallsignInfo "{68B70BB5E557E33A}" {
   m_sCallsign "Bandit-2"
  }
  SCR_CallsignInfo "{68B70BB5E557A2CB}" {
   m_sCallsign "Bandit-3"
  }
  SCR_CallsignInfo "{68B70BB5E557A2C8}" {
   m_sCallsign "Bandit-4"
  }
 }
 m_sCallsignGroupFormat "%3"
 m_sCallsignCharacterFormat "%3"
 m_aCharacterRoleCallsigns {
  SCR_LeaderRoleCallsign "{68B70BB5E557A2C9}" {
   m_sRoleName "#AR-Callsign_US_SquadLeader"
  }
  SCR_RadioOperatorRoleCallsign "{68B70BB5E557A2CE}" {
   m_sRoleName "#AR-Callsign_US_RadioOperator"
  }
  SCR_PlayerLeaderRoleCallsign "{68B70BB5E557A2CF}" {
   m_bEnabled 0
   m_sRoleName "#AR-Callsign_US_SquadLeader"
   m_eRoleAvailableForCharacterType PLAYER_ONLY
  }
 }
}