SCR_FactionCallsignInfo {
 m_bIsAssignedRandomly 0
 m_aCompanyNames {
  SCR_CallsignInfo "{68CB61C8925CA20F}" {
   m_sCallsign "7CAV "
  }
 }
 m_iCompanyOverflowIndex 1
 m_aPlatoonNames {
  SCR_CallsignInfo "{68CB61C8925CA21A}" {
   m_sCallsign " Drill Instructors"
  }
  SCR_CallsignInfo "{68CB61C8925CA21B}" {
   m_sCallsign "Recruits"
  }
 }
 m_aSquadNames {
  SCR_CallsignInfo "{68CB61C8925CA264}" {
   m_sCallsign "Godfather-6"
  }
  SCR_CallsignInfo "{68CB61C8925CA265}" {
   m_sCallsign "Godfather-5"
  }
  SCR_CallsignInfo "{68CB61C8925CA266}" {
   m_sCallsign "Godfather-7"
  }
  SCR_CallsignInfo "{68CB61C8925CBECA}" {
   m_sCallsign "Pegasus-6"
  }
  SCR_CallsignInfo "{68CB61C8925CBECB}" {
   m_sCallsign "Pegasus-5"
  }
  SCR_CallsignInfo "{68CB61C8925CBECC}" {
   m_sCallsign "Pegasus-7"
  }
  SCR_CallsignInfo "{68CB61C8925CBECD}" {
   m_sCallsign "Warhorse-6"
  }
  SCR_CallsignInfo "{68CB61C8C626D802}" {
   m_sCallsign "Warhorse-5"
  }
  SCR_CallsignInfo "{68CB61C8C6F6CEB3}" {
   m_sCallsign "Warhorse-7"
  }
  SCR_CallsignInfo "{68CB61C8C68F1F07}" {
   m_sCallsign "Hitman-6"
  }
  SCR_CallsignInfo "{68CB61C8C5569CBE}" {
   m_sCallsign "Hitman-5"
  }
  SCR_CallsignInfo "{68CB61C8C574E853}" {
   m_sCallsign "Hitman-7"
  }
 }
 m_sCallsignGroupFormat "%3"
 m_sCallsignCharacterFormat "%3"
 m_aCharacterRoleCallsigns {
  SCR_LeaderRoleCallsign "{68CB61C8925CBECE}" {
   m_sRoleName "#AR-Callsign_US_SquadLeader"
  }
  SCR_RadioOperatorRoleCallsign "{68CB61C8925CBECF}" {
   m_sRoleName "#AR-Callsign_US_RadioOperator"
  }
  SCR_PlayerLeaderRoleCallsign "{68CB61C8925CBEC0}" {
   m_bEnabled 0
   m_sRoleName "#AR-Callsign_US_SquadLeader"
   m_eRoleAvailableForCharacterType PLAYER_ONLY
  }
 }
}