SCR_FactionCallsignInfo {
 m_bIsAssignedRandomly 0
 m_aCompanyNames {
  SCR_CallsignInfo "{68B70BB14321590B}" {
   m_sCallsign "7CAV "
  }
 }
 m_iCompanyOverflowIndex 1
 m_aPlatoonNames {
  SCR_CallsignInfo "{68B70BB143215972}" {
   m_sCallsign " Drill Instructors"
  }
  SCR_CallsignInfo "{68B70BB143215973}" {
   m_sCallsign "Recruits"
  }
 }
 m_aSquadNames {
  SCR_CallsignInfo "{68B70BB143215970}" {
   m_sCallsign "Viking-6"
  }
  SCR_CallsignInfo "{68B70BB143215971}" {
   m_sCallsign "Viking-5"
  }
  SCR_CallsignInfo "{68B70BB1432EB514}" {
   m_sCallsign "Viking-7"
  }
  SCR_CallsignInfo "{68B70BB1432EB513}" {
   m_sCallsign "Viking-1"
  }
  SCR_CallsignInfo "{68B70BB1432EB512}" {
   m_sCallsign "Viking-2"
  }
  SCR_CallsignInfo "{68B70BB1432EB511}" {
   m_sCallsign "Viking-3"
  }
  SCR_CallsignInfo "{68B70BB1432E8999}" {
   m_sCallsign "Viking-4"
  }
  SCR_CallsignInfo "{68B70BB2A53F1FDE}" {
   m_sCallsign "Banshee-1"
  }
  SCR_CallsignInfo "{68B70BB2A5C383AF}" {
   m_sCallsign "Banshee-2"
  }
  SCR_CallsignInfo "{68B70BB2A5922677}" {
   m_sCallsign "Banshee-3"
  }
  SCR_CallsignInfo "{68B70BB2A5ABE122}" {
   m_sCallsign "Banshee-4"
  }
 }
 m_sCallsignGroupFormat "%3"
 m_sCallsignCharacterFormat "%3"
 m_aCharacterRoleCallsigns {
  SCR_LeaderRoleCallsign "{68B70BB1432E8998}" {
   m_sRoleName "#AR-Callsign_US_SquadLeader"
  }
  SCR_RadioOperatorRoleCallsign "{68B70BB1432E8996}" {
   m_sRoleName "#AR-Callsign_US_RadioOperator"
  }
  SCR_PlayerLeaderRoleCallsign "{68B70BB1432E3591}" {
   m_bEnabled 0
   m_sRoleName "#AR-Callsign_US_SquadLeader"
   m_eRoleAvailableForCharacterType PLAYER_ONLY
  }
 }
}