SCR_FactionCallsignInfo {
 m_bIsAssignedRandomly 0
 m_aCompanyNames {
  SCR_CallsignInfo "{68B70BB4DD1244AD}" {
   m_sCallsign "7CAV "
  }
 }
 m_iCompanyOverflowIndex 1
 m_aPlatoonNames {
  SCR_CallsignInfo "{68B70BB4DD1244BA}" {
   m_sCallsign " Drill Instructors"
  }
  SCR_CallsignInfo "{68B70BB4DD1244BB}" {
   m_sCallsign "Recruits"
  }
 }
 m_aSquadNames {
  SCR_CallsignInfo "{68B70BB4DD124484}" {
   m_sCallsign "Gunslinger-6"
  }
  SCR_CallsignInfo "{68B70BB4DD124485}" {
   m_sCallsign "Gunslinger-5"
  }
  SCR_CallsignInfo "{68B70BB4DD126CC4}" {
   m_sCallsign "Gunslinger-7"
  }
  SCR_CallsignInfo "{68B70BB4DD126CC7}" {
   m_sCallsign "Gunslinger-1"
  }
  SCR_CallsignInfo "{68B70BB4C900EC75}" {
   m_sCallsign "Gunslinger-2"
  }
  SCR_CallsignInfo "{68B70BB4C920AEA6}" {
   m_sCallsign "Gunslinger-3"
  }
  SCR_CallsignInfo "{68B70BB4C9C65E3E}" {
   m_sCallsign "Gunslinger-4"
  }
 }
 m_sCallsignGroupFormat "%3"
 m_sCallsignCharacterFormat "%3"
 m_aCharacterRoleCallsigns {
  SCR_LeaderRoleCallsign "{68B70BB4DD126CC6}" {
   m_sRoleName "#AR-Callsign_US_SquadLeader"
  }
  SCR_RadioOperatorRoleCallsign "{68B70BB4DD126CC0}" {
   m_sRoleName "#AR-Callsign_US_RadioOperator"
  }
  SCR_PlayerLeaderRoleCallsign "{68B70BB4DD12D924}" {
   m_bEnabled 0
   m_sRoleName "#AR-Callsign_US_SquadLeader"
   m_eRoleAvailableForCharacterType PLAYER_ONLY
  }
 }
}