SCR_FactionPlayerLoadout : "{1512CA50603780F1}Prefabs/Characters/Cav_Factions/Bravo/Loadouts/Viking/Loadout_B_Rifleman_Viking.conf" {
 m_sLoadoutName "Engineer"
 m_sLoadoutResource "{EB4A9B3E61E30139}Prefabs/Characters/Cav_Factions/Bravo/Bravo_Engineer.et"
 m_sAffiliatedFaction "Helios"
}