SCR_EntityCatalogMultiList {
 m_eEntityCatalogType ITEM
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{68B438662D20ED91}" {
   m_sIdentifier "Weapons"
   m_aEntities {
    SCR_EntityCatalogEntry "{68B438660E9DDC88}" {
     m_sEntityPrefab "{3E413771E1834D2F}Prefabs/Weapons/Rifles/M16/Rifle_M16A2.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B43866738EAD88}" {
       m_eItemMode WEAPON
       m_iSupplyCost 0
       m_bUseMilitarySupplyAllocation 0
      }
     }
    }
    SCR_EntityCatalogEntry "{68B43866587CBC73}" {
     m_sEntityPrefab "{8069A3DF6410FDDF}Prefabs/Weapons/Handguns/M17/Handgun_M17.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B43865A3052B93}" {
       m_eItemType PISTOL
       m_eItemMode WEAPON
       m_iSupplyCost 0
       m_bUseMilitarySupplyAllocation 0
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{68B43865B4847E20}" {
   m_sIdentifier "Ammunition"
   m_aEntities {
    SCR_EntityCatalogEntry "{68B43865A8EFF3A9}" {
     m_sEntityPrefab "{8FF49793853DB2F9}Prefabs/Weapons/Magazines/m17_magazines/Magazine_9x19_m17_17rnd_M1152.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B4386581DEE636}" {
       m_eItemType PISTOL
       m_eItemMode AMMUNITION
       m_iSupplyCost 0
       m_bUseMilitarySupplyAllocation 0
      }
     }
    }
    SCR_EntityCatalogEntry "{68B43865F230B98C}" {
     m_sEntityPrefab "{FB5EB0F6D447E858}Prefabs/Weapons/Magazines/Magazine_556x45_STANAG_30rnd_M193_Ball.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B43865F230B9F0}" {
       m_eItemMode AMMUNITION
       m_iSupplyCost 0
       m_bUseMilitarySupplyAllocation 0
      }
     }
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{68B43865D93076B3}" {
   m_sIdentifier "Explosives"
   m_aEntities {
    SCR_EntityCatalogEntry "{68B43865D2D17A97}" {
     m_sEntityPrefab "{E8F00BF730225B00}Prefabs/Weapons/Grenades/Grenade_M67.et"
     m_aEntityDataList {
      SCR_ArsenalItem "{68B43865C7A0C983}" {
       m_eItemType LETHAL_THROWABLE
       m_iSupplyCost 0
       m_bUseMilitarySupplyAllocation 0
      }
     }
    }
   }
  }
 }
}