SCR_EntityCatalog {
 m_eEntityCatalogType WEAPONS_TRIPOD
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{68A52AECE03AE6AC}" {
   m_sEntityPrefab "{9B625CAE6DEE1DAB}Prefabs/Items/Equipment/Tripods/M2/Part_M2_Gun.et"
  }
  SCR_EntityCatalogEntry "{68A52AECE14919A9}" {
   m_sEntityPrefab "{6A3EF260029FE220}Prefabs/Items/Equipment/Tripods/M2/Part_M3_Tripod.et"
  }
  SCR_EntityCatalogEntry "{68A52AECECDB9A60}" {
   m_sEntityPrefab "{62B704DD79A3B5BE}Prefabs/Items/Equipment/Mortars/M252/Part_M252_Barrel.et"
  }
  SCR_EntityCatalogEntry "{68A52AECEDDA666C}" {
   m_sEntityPrefab "{0D540E16A6E53433}Prefabs/Items/Equipment/Mortars/M252/Part_M252_BasePlate.et"
  }
  SCR_EntityCatalogEntry "{68A52AECED01FB19}" {
   m_sEntityPrefab "{80D38046CB4D4663}Prefabs/Items/Equipment/Mortars/M252/Part_M252_Bipod.et"
  }
  SCR_EntityCatalogEntry "{68A52AECE2B5A968}" {
   m_sEntityPrefab "{EF55A296E50DC8B8}Prefabs/Items/Equipment/Tripods/M60/Part_Tripod_M122.et"
  }
  SCR_EntityCatalogEntry "{68A52AECE3F394D0}" {
   m_sEntityPrefab "{1742632597955A55}Prefabs/Items/Misc/Sandbags/Part_Sandbag_Plastic.et"
  }
 }
}