SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{662C28AA4BAD7217}" {
   m_sIdentifier "HeliosHMMWVs"
   m_aEntities {
    SCR_EntityCatalogEntry "{662C28AA5D820FFC}" {
     m_sEntityPrefab "{0C83247826E637DF}Prefabs/Vehicles/Wheeled/M998/M1113_Helios.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{669B3A99D69282A5}" {
      }
     }
    }
    SCR_EntityCatalogEntry "{662C28AA59B139EB}" {
     m_sEntityPrefab "{570922FC45896FC0}Prefabs/Vehicles/Wheeled/M998/M1113_Helios_All.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{669B3A99DAFB379B}" {
      }
     }
    }
    SCR_EntityCatalogEntry "{662C28AA5AE95042}" {
     m_sEntityPrefab "{365CBDB5FEC71EAD}Prefabs/Vehicles/Wheeled/M998/M1113_Helios_All_Tan.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{669B3A9926E27097}" {
      }
     }
    }
    SCR_EntityCatalogEntry "{662C28AA5BEC8E2D}" {
     m_sEntityPrefab "{65E09B39BE5C1C13}Prefabs/Vehicles/Wheeled/M998/M1113_Helios_Hauler.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{669B3A9922DAC559}" {
      }
     }
    }
    SCR_EntityCatalogEntry "{662C28AA5B49D5F7}" {
     m_sEntityPrefab "{9CEB910915CE4E22}Prefabs/Vehicles/Wheeled/M998/M1113_Helios_Hauler_Tan.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{669B3A992E28DB21}" {
      }
     }
    }
    SCR_EntityCatalogEntry "{662C28ABA7721BB7}" {
     m_sEntityPrefab "{D23F76365B2218D2}Prefabs/Vehicles/Wheeled/M998/M1113_Helios_Tan.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{669B3A992907F016}" {
      }
     }
    }
    SCR_EntityCatalogEntry "{662C28ABAF8B60D4}" {
     m_sEntityPrefab "{AA7C84005F853973}Prefabs/Vehicles/Wheeled/M998/M1114_Mule_Helios.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{669B3A993692AC95}" {
      }
     }
    }
    SCR_EntityCatalogEntry "{662C28ABA8D172FF}" {
     m_sEntityPrefab "{9FAC2CB9B68DBA0E}Prefabs/Vehicles/Wheeled/M998/M1114_Mule_Tan.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{669B3A99301A020F}" {
      }
     }
    }
   }
  }
 }
}