SCR_MissionHeader {
 World "{335375F3D2D0A9D2}Worlds/7Cav_Training_FtTharen.ent"
 m_sName "7Cav Bootcamp and Training"
 m_sAuthor "S3 Dev Team"
 m_sDescription "<Insert world description>"
 m_sIcon "{D7362DD05442894C}Images/cav2.edds"
 m_sLoadingScreen "{D7362DD05442894C}Images/cav2.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
}