SCR_MissionHeader {
 World "{167C30C5A31AE6E3}Worlds/7Cav_SB_FaircroftIslands.ent"
 m_sName "7Cav Sandbox Faircroft Islands"
 m_sAuthor "S3 Dev team"
 m_sDescription "<Insert world description>"
 m_sIcon "{D7362DD05442894C}Images/cav2.edds"
 m_sLoadingScreen "{D7362DD05442894C}Images/cav2.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 128
}