SCR_MissionHeader {
 World "{CAB15D189F522B81}Worlds/7Cav_SB_BackwoodsNC.ent"
 m_sName "7Cav Sandbox Back Country"
 m_sAuthor "S3 Dev Team"
 m_sDescription "<Insert world description>"
 m_sIcon "{D7362DD05442894C}Images/cav2.edds"
 m_sLoadingScreen "{D7362DD05442894C}Images/cav2.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 128
}