SCR_MissionHeader {
 World "{7A07FFF2664BC336}Worlds/7Cav_SB_Gogland.ent"
 m_sName "7Cav Sandbox Gogland"
 m_sAuthor "S3 Dev Team"
 m_sDescription "<Insert world description>"
 m_sIcon "{D7362DD05442894C}Images/cav2.edds"
 m_sLoadingScreen "{D7362DD05442894C}Images/cav2.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 128
}