SCR_MissionHeader {
 World "{B431A9D4A5FAD324}Worlds/7Cav_SB_FortTharen.ent"
 m_sName "7CAV Sandbox Fort Tharen"
 m_sAuthor "S3 Dev Team"
 m_sDescription "<Insert world description>"
 m_sIcon "{D7362DD05442894C}Images/cav2.edds"
 m_sLoadingScreen "{D7362DD05442894C}Images/cav2.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 128
}