SCR_MissionHeader {
 World "{36DE2439603E6A8F}Worlds/7Cav_SB_Bergamo.ent"
 m_sName "7Cav Sandbox Bergamo"
 m_sAuthor "S3 Dev Team"
 m_sDescription "<Insert world description>"
 m_sIcon "{D7362DD05442894C}Images/cav2.edds"
 m_sLoadingScreen "{D7362DD05442894C}Images/cav2.edds"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 128
}