SCR_MilitarySupplyAllocationConfig {
 m_aMilitarySupplyAllocationRankList {
  SCR_MilitarySupplyAllocationRankInfo "{659473327FA32FA1}" {
   m_iMilitarySupplyAllocationValue 1000
   m_iAvailableAllocatedSuppliesReplenishmentThresholdValue 1000
  }
  SCR_MilitarySupplyAllocationRankInfo "{659473327FA32FA5}" {
   m_iMilitarySupplyAllocationValue 1000
   m_iAvailableAllocatedSuppliesReplenishmentThresholdValue 1000
  }
  SCR_MilitarySupplyAllocationRankInfo "{659473327FA32FA6}" {
   m_iMilitarySupplyAllocationValue 1000
   m_iAvailableAllocatedSuppliesReplenishmentThresholdValue 1000
  }
  SCR_MilitarySupplyAllocationRankInfo "{659473327FA32FA7}" {
   m_iMilitarySupplyAllocationValue 1000
   m_iAvailableAllocatedSuppliesReplenishmentThresholdValue 1000
  }
  SCR_MilitarySupplyAllocationRankInfo "{659473327FA32FA8}" {
   m_iMilitarySupplyAllocationValue 1000
   m_iAvailableAllocatedSuppliesReplenishmentThresholdValue 1000
  }
  SCR_MilitarySupplyAllocationRankInfo "{659473327FA32FA9}" {
   m_iMilitarySupplyAllocationValue 1000
   m_iAvailableAllocatedSuppliesReplenishmentThresholdValue 999
  }
  SCR_MilitarySupplyAllocationRankInfo "{661040430C569C66}" {
   m_iMilitarySupplyAllocationValue 1000
   m_iAvailableAllocatedSuppliesReplenishmentThresholdValue 1000
  }
  SCR_MilitarySupplyAllocationRankInfo "{661040430D10B2F8}" {
   m_iMilitarySupplyAllocationValue 1000
  }
 }
}