SCR_Faction : "{7D3FEF4E243F3587}Configs/Factions/Charlie/Charlie_Faction_Base.conf" {
 FactionKey "Command"
 UIInfo SCR_FactionUIInfo "{66493AE5A64FA07C}" {
  Name "Command"
  Icon "{01CF1572F9E5F146}Images/1BN.edds"
  m_sNameUpper "COMMAND"
 }
 m_iOrder 12
 m_CallsignInfo SCR_FactionCallsignInfo "{66493AE743F887BC}" : "{E619424C2F1BEB4A}Configs/Callsigns/Callsigns_Command.conf" {
  m_sCallsignCharacterWithRoleFormat ""
 }
 m_aPredefinedGroups {
  SCR_GroupPreset "{68CB61C802AA9DD9}" {
   m_sGroupName "Godfather-6"
   m_sGroupDescription "CO, RTO"
   m_iGroupSize 2
   m_iRadioFrequency 68200
  }
  SCR_GroupPreset "{68CB61C802AA9DD3}" {
   m_sGroupName "Godfather-5"
   m_sGroupDescription "XO, RTO"
   m_iGroupSize 2
   m_iRadioFrequency 68200
  }
  SCR_GroupPreset "{68CB61C802AA9DD5}" {
   m_sGroupName "Godfather-7"
   m_sGroupDescription "CSM, RTO"
   m_iGroupSize 2
   m_iRadioFrequency 68200
  }
  SCR_GroupPreset "{68CB61C802AA1A1A}" {
   m_sGroupName "Pegasus-1"
   m_sGroupDescription "CO, RTO"
   m_iGroupSize 2
   m_iRadioFrequency 60000
  }
  SCR_GroupPreset "{68CB61C802AA1A19}" {
   m_sGroupName "Pegasus-5"
   m_sGroupDescription "XO, RTO"
   m_iGroupSize 2
   m_iRadioFrequency 60000
  }
  SCR_GroupPreset "{68CB61C802AA1A18}" {
   m_sGroupName "Pegasus-7"
   m_sGroupDescription "1SG, RTO"
   m_iGroupSize 1
   m_iRadioFrequency 60000
  }
  SCR_GroupPreset "{68CB61C802AA1A27}" {
   m_sGroupName "Warhorse-6"
   m_sGroupDescription "CO/RTO"
   m_iGroupSize 2
   m_iRadioFrequency 49000
  }
  SCR_GroupPreset "{68CB61CAAD80DFC4}" {
   m_sGroupName "Warhorse-5"
   m_sGroupDescription "XO/RTO"
   m_iGroupSize 2
   m_iRadioFrequency 49000
  }
  SCR_GroupPreset "{68CB61CA9AEC7B84}" {
   m_sGroupName "Warhorse-7"
   m_sGroupDescription "1SG/RTO"
   m_iGroupSize 2
   m_iRadioFrequency 49000
  }
  SCR_GroupPreset "{68CB61CAFD91E53C}" {
   m_sGroupName "Hitman-6"
   m_sGroupDescription "CO/RTO"
   m_iGroupSize 2
   m_iRadioFrequency 59000
  }
  SCR_GroupPreset "{68CB61CAE9CBBBE1}" {
   m_sGroupName "Hitman-5"
   m_sGroupDescription "XO/RTO"
   m_iGroupSize 2
   m_iRadioFrequency 59000
  }
  SCR_GroupPreset "{68CB61CADB256AFF}" {
   m_sGroupName "Hitman-7"
   m_sGroupDescription "1SG/RTO"
   m_iGroupSize 2
   m_iRadioFrequency 59000
  }
 }
 m_iFactionRadioFrequency 68000
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{664951A78E2E84F6}" : "{715DDAAD87B11B2F}Configs/Factions/Charlie/Catalogs/Characters_EntityCatalog_Charlie.conf" {
  }
  SCR_EntityCatalogMultiList "{68CB61CA3CD4551E}" : "{2DD7CB4BD8228AC2}Configs/Factions/Charlie/Catalogs/Items_EntityCatalog_Charlie.conf" {
  }
 }
}